// Mapping from book paths (relative to books/) to English slug names.
// Used by extraction scripts and migration tools.
//
// Convention: transliterated Hebrew, lowercase, hyphens between words.
// Short and recognizable. No "sefer-" prefix unless it's part of the common name.

const fs = require("fs");
const path = require("path");

// Book path (relative to books/, without .md) → English slug
const SLUG_MAP = {
  // ── Breslov ──────────────────────────────────────────────────────────────
  "breslov/eretz-yisrael/eretz-yisrael-1":     "eretz-yisrael-1",
  "breslov/eretz-yisrael/eretz-yisrael-2":     "eretz-yisrael-2",
  "breslov/chayei-moharan":                     "chayei-moharan",
  "breslov/likutei-halachot":                   "likutei-halachot",
  "breslov/likutei-halachot-taanot":            "likutei-halachot-taanot",
  "breslov/likutei-moharan":                    "likutei-moharan",
  "breslov/likutei-etzot":                      "likutei-etzot",
  "breslov/likutei-tefilot":                    "likutei-tefilot",
  "breslov/meshivat-nefesh":                    "meshivat-nefesh",
  "breslov/sipurei-maasiyot":                   "sipurei-maasiyot",
  "breslov/sefer-hamidot":                      "sefer-hamidot",
  "breslov/yemei-moharnat/yemei-moharnat-1":    "yemei-moharnat-1",
  "breslov/yemei-moharnat/yemei-moharnat-2":    "yemei-moharnat-2",
  "breslov/shemot-hatzadikim":                  "shemot-hatzadikim",
  "breslov/alim-letrufa":                       "alim-letrufa",
  "breslov/shivchei-haran":                     "shivchei-haran",
  "breslov/sichot-haran":                       "sichot-haran",

  // ── Kabbalah: standalone ─────────────────────────────────────────────────
  "kabbala/igeret-vezot-leyehuda":              "igeret-vezot-leyehuda",
  "kabbala/or-hasechel":                        "or-hasechel",
  "kabbala/get-hashemot":                       "get-hashemot",
  "kabbala/gan-naul":                           "gan-naul",
  "kabbala/drashat-haramban":                   "drashat-haramban",
  "kabbala/heichalot-rabati":                   "heichalot-rabati",
  "kabbala/sefer-habahir":                      "sefer-habahir",
  "kabbala/sefer-hacheshek":                    "sefer-hacheshek",

  // ── Baal HaSulam ─────────────────────────────────────────────────────────
  "kabbala/baal-hasulam/or-pnimi":                    "or-pnimi",
  "kabbala/baal-hasulam/hearot-kuntres-matan-torah":  "hearot-kuntres-matan-torah",
  "kabbala/baal-hasulam/hearot-talmud-eser-hasfirot": "hearot-talmud-eser-hasfirot",
  "kabbala/baal-hasulam/hakdamot-chochmat-haemet":    "hakdamot-chochmat-haemet",
  "kabbala/baal-hasulam/hashpaa/hearot-hashpaa":      "hearot-hashpaa",
  "kabbala/baal-hasulam/hashpaa/hashpaa":             "hashpaa",
  "kabbala/baal-hasulam/mavo-lesefer-hazohar":        "mavo-lesefer-hazohar",
  "kabbala/baal-hasulam/pticha-lechochmat-hakabbala": "pticha-lechochmat-hakabbala",
  "kabbala/baal-hasulam/pticha-lepirush-hasulam":     "pticha-lepirush-hasulam",
  "kabbala/baal-hasulam/kuntres-matan-torah":         "kuntres-matan-torah",
  "kabbala/baal-hasulam/talmud-eser-hasfirot":        "talmud-eser-hasfirot",

  // ── Zohar ────────────────────────────────────────────────────────────────
  "kabbala/zohar/idra-zuta":                          "idra-zuta",
  "kabbala/zohar/or-hachama":                         "or-hachama",
  "kabbala/zohar/biur-hagra-sifra-detzniuta":         "biur-hagra-sifra-detzniuta",
  "kabbala/zohar/idrot":                              "idrot",
  "kabbala/zohar/hasulam-al-hazohar":                 "hasulam-al-hazohar",
  "kabbala/zohar/hearot-or-hachama":                  "hearot-or-hachama",
  "kabbala/zohar/zohar-chadash":                      "zohar-chadash",
  "kabbala/zohar/zohar-meturgam/zohar-meturgam-bamidbar":  "zohar-meturgam-bamidbar",
  "kabbala/zohar/zohar-meturgam/zohar-meturgam-bereshit":  "zohar-meturgam-bereshit",
  "kabbala/zohar/zohar-meturgam/zohar-meturgam-devarim":   "zohar-meturgam-devarim",
  "kabbala/zohar/zohar-meturgam/zohar-meturgam-hakdama":   "zohar-meturgam-hakdama",
  "kabbala/zohar/zohar-meturgam/zohar-meturgam-vayikra":   "zohar-meturgam-vayikra",
  "kabbala/zohar/zohar-meturgam/zohar-meturgam-chadash":   "zohar-meturgam-chadash",
  "kabbala/zohar/zohar-meturgam/zohar-meturgam-shemot":    "zohar-meturgam-shemot",
  "kabbala/zohar/zohar-meturgam/zohar-meturgam-tikunim":   "zohar-meturgam-tikunim",
  "kabbala/zohar/yahel-or":                           "yahel-or",
  "kabbala/zohar/ketem-paz":                          "ketem-paz",
  "kabbala/zohar/mikdash-melech":                     "mikdash-melech",
  "kabbala/zohar/mikdash-melech-remez":               "mikdash-melech-remez",
  "kabbala/zohar/nefesh-david":                       "nefesh-david",
  "kabbala/zohar/sefer-hazohar":                      "sefer-hazohar",
  "kabbala/zohar/sifra-detzniuta-biur-hagra":         "sifra-detzniuta-biur-hagra",
  "kabbala/zohar/sifra-detzniuta":                    "sifra-detzniuta",
  "kabbala/zohar/tikunei-hazohar":                    "tikunei-hazohar",

  // ── Arizal & Chaim Vital ─────────────────────────────────────────────────
  "kabbala/arizal/hearot-shaar-ruach-hakodesh":       "hearot-shaar-ruach-hakodesh",
  "kabbala/arizal/etz-chaim":                         "etz-chaim",
  "kabbala/arizal/pri-etz-chaim":                     "pri-etz-chaim",
  "kabbala/arizal/shaar-hagilgulim":                  "shaar-hagilgulim",
  "kabbala/arizal/shaar-hahakdamot":                  "shaar-hahakdamot",
  "kabbala/arizal/shaar-hakavanot":                   "shaar-hakavanot",
  "kabbala/arizal/shaar-hamitzvot":                   "shaar-hamitzvot",
  "kabbala/arizal/shaar-hapsukim":                    "shaar-hapsukim",
  "kabbala/arizal/shaar-maamarei-razal":              "shaar-maamarei-razal",
  "kabbala/arizal/shaar-maamarei-rashbi":             "shaar-maamarei-rashbi",
  "kabbala/arizal/shaar-ruach-hakodesh":              "shaar-ruach-hakodesh",
  "kabbala/arizal/shaarei-kedusha":                   "shaarei-kedusha",

  // ── Abulafia ─────────────────────────────────────────────────────────────
  "kabbala/abulafia/otzar-eden-haganuz":              "otzar-eden-haganuz",
  "kabbala/abulafia/or-hasechel-abulafia":            "or-hasechel-abulafia",
  "kabbala/abulafia/imrei-shefer":                    "imrei-shefer",
  "kabbala/abulafia/chayei-haolam-haba":              "chayei-haolam-haba",
  "kabbala/abulafia/sheva-netivot-hatorah":           "sheva-netivot-hatorah",

  // ── Sefer Yetzira ────────────────────────────────────────────────────────
  "kabbala/sefer-yetzira/sefer-yetzira":              "sefer-yetzira",
  "kabbala/sefer-yetzira/sefer-yetzira-mesudar":      "sefer-yetzira-mesudar",
  "kabbala/sefer-yetzira/sefer-yetzira-nusach-hagra": "sefer-yetzira-nusach-hagra",
  "kabbala/sefer-yetzira/mefarshim/pirush-hagra-yetzira":          "pirush-hagra-yetzira",
  "kabbala/sefer-yetzira/mefarshim/pirush-haraavad-yetzira":       "pirush-haraavad-yetzira",
  "kabbala/sefer-yetzira/mefarshim/pirush-riaz-yetzira":           "pirush-riaz-yetzira",
  "kabbala/sefer-yetzira/mefarshim/pirush-haramak-yetzira":        "pirush-haramak-yetzira",
  "kabbala/sefer-yetzira/mefarshim/pirush-maaseh-bereshit":        "pirush-maaseh-bereshit",
  "kabbala/sefer-yetzira/mefarshim/pirush-ri-sagi-nahor-yetzira":  "pirush-ri-sagi-nahor-yetzira",
  "kabbala/sefer-yetzira/mefarshim/pri-yitzchak-yetzira":          "pri-yitzchak-yetzira",
  "kabbala/sefer-yetzira/mefarshim/ramban-yetzira":                "ramban-yetzira",
  "kabbala/sefer-yetzira/mefarshim/rasag-yetzira":                 "rasag-yetzira",

  // ── More Kabbalah ────────────────────────────────────────────────────────
  "kabbala/more-kabbala/igeret-el-haramban":          "igeret-el-haramban",
  "kabbala/more-kabbala/biur-eser-sfirot":            "biur-eser-sfirot",
  "kabbala/more-kabbala/benafesh-david":              "benafesh-david",
  "kabbala/more-kabbala/hearot-klalei-hatchalat-hachochma": "hearot-klalei-hatchalat-hachochma",
  "kabbala/more-kabbala/hearot-zohar-harakia":        "hearot-zohar-harakia",
  "kabbala/more-kabbala/vayilket-yosef":              "vayilket-yosef",
  "kabbala/more-kabbala/chesed-leavraham":            "chesed-leavraham",
  "kabbala/more-kabbala/yosher-levav":                "yosher-levav",
  "kabbala/more-kabbala/klalei-hatchalat-hachochma":  "klalei-hatchalat-hachochma",
  "kabbala/more-kabbala/zohar-harakia":               "zohar-harakia",
  "kabbala/more-kabbala/mavo-shearim":                "mavo-shearim",
  "kabbala/more-kabbala/magid-mesharim":              "magid-mesharim",
  "kabbala/more-kabbala/megale-amukot-vaetchanan":    "megale-amukot-vaetchanan",
  "kabbala/more-kabbala/mitpachat-sfarim":            "mitpachat-sfarim",
  "kabbala/more-kabbala/maarechet-haelokut":          "maarechet-haelokut",
  "kabbala/more-kabbala/maaseh-rokeach":              "maaseh-rokeach",
  "kabbala/more-kabbala/sod-hanevua":                 "sod-hanevua",
  "kabbala/more-kabbala/sod-yediat-hametziyut":       "sod-yediat-hametziyut",
  "kabbala/more-kabbala/sefer-hayichud":              "sefer-hayichud",
  "kabbala/more-kabbala/sefer-haiyun":                "sefer-haiyun",
  "kabbala/more-kabbala/sefer-hapliah":               "sefer-hapliah",
  "kabbala/more-kabbala/sefer-hakana":                "sefer-hakana",
  "kabbala/more-kabbala/sefer-hatmuna":               "sefer-hatmuna",
  "kabbala/more-kabbala/midrash-shimon-hatzadik":     "midrash-shimon-hatzadik",
  "kabbala/more-kabbala/meulefet-sapirim":            "meulefet-sapirim",
  "kabbala/more-kabbala/shoshan-sodot":               "shoshan-sodot",
  "kabbala/more-kabbala/avodat-hakodesh":             "avodat-hakodesh",
  "kabbala/more-kabbala/lev-netivot":                 "lev-netivot",
  "kabbala/more-kabbala/pri-etz-hadar":               "pri-etz-hadar",
  "kabbala/more-kabbala/kitzur-machberet-hakodesh":   "kitzur-machberet-hakodesh",
  "kabbala/more-kabbala/reshit-chochma":              "reshit-chochma",
  "kabbala/more-kabbala/recanati-al-hatorah":         "recanati-al-hatorah",
  "kabbala/more-kabbala/shuvi-shuvi-hashulamit":      "shuvi-shuvi-hashulamit",
  "kabbala/more-kabbala/shomer-emunim":               "shomer-emunim",
  "kabbala/more-kabbala/shaarei-ora":                 "shaarei-ora",
  "kabbala/more-kabbala/shaarei-tzedek":              "shaarei-tzedek",
  "kabbala/more-kabbala/tolaat-yaakov":               "tolaat-yaakov",

  // ── Individual authors ───────────────────────────────────────────────────
  "kabbala/avraham-mekolonia/keter-shem-tov":         "keter-shem-tov",
  "kabbala/avraham-merimon/brit-menucha":              "brit-menucha",
  "kabbala/chaim-vital/likutei-hashas":               "likutei-hashas",
  "kabbala/chaim-vital/etz-hadaat-tov":               "etz-hadaat-tov",
  "kabbala/gikatilla/sod-hanachash":                  "sod-hanachash",
  "kabbala/gikatilla/sefer-hachashmal":               "sefer-hachashmal",
  "kabbala/gikatilla/shaar-hanikud":                  "shaar-hanikud",
  "kabbala/meir-ibn-gabbai/derech-emuna":             "derech-emuna",
  "kabbala/menachem-azaria-mipano/gilgulei-neshamot": "gilgulei-neshamot",
  "kabbala/menachem-azaria-mipano/yonat-elem":        "yonat-elem",
  "kabbala/menachem-azaria-mipano/asara-maamarot":    "asara-maamarot",
  "kabbala/moshe-de-leon/shekel-hakodesh":            "shekel-hakodesh",
  "kabbala/shalom-sharabi/nahar-shalom":              "nahar-shalom",
  "kabbala/shalom-sharabi/chasdei-david":             "chasdei-david",

  // ── Ramchal ──────────────────────────────────────────────────────────────
  "kabbala/ramchal/biurim-otzrot-chaim":              "biurim-otzrot-chaim",
  "kabbala/ramchal/divrei-torah-magid-ramchal":       "divrei-torah-magid-ramchal",
  "kabbala/ramchal/daat-tvunot":                      "daat-tvunot",
  "kabbala/ramchal/derech-etz-chaim":                 "derech-etz-chaim",
  "kabbala/ramchal/klalut-sharshei-hachochma":        "klalut-sharshei-hachochma",
  "kabbala/ramchal/klalei-maamar-hachochma":          "klalei-maamar-hachochma",
  "kabbala/ramchal/klalei-milchamot-moshe":           "klalei-milchamot-moshe",
  "kabbala/ramchal/klalei-kinat-hashem":              "klalei-kinat-hashem",
  "kabbala/ramchal/klalei-pitchei-chochma":           "klalei-pitchei-chochma",
  "kabbala/ramchal/likutim-kitvei-ramchal":           "likutim-kitvei-ramchal",
  "kabbala/ramchal/maamar-hachochma":                 "maamar-hachochma",
  "kabbala/ramchal/maamar-vayehi-miketz":             "maamar-vayehi-miketz",
  "kabbala/ramchal/maamar-chochmat-haemet":           "maamar-chochmat-haemet",
  "kabbala/ramchal/maamar-al-hahagadot":              "maamar-al-hahagadot",
  "kabbala/ramchal/sod-hamerkava":                    "sod-hamerkava",
  "kabbala/ramchal/derech-chochma":                   "derech-chochma",
  "kabbala/ramchal/mishknei-elyon":                   "mishknei-elyon",
  "kabbala/ramchal/pinot-hamerkava":                  "pinot-hamerkava",
  "kabbala/ramchal/kinat-hashem-tzevaot":             "kinat-hashem-tzevaot",
  "kabbala/ramchal/asara-orot":                       "asara-orot",
  "kabbala/ramchal/asara-prakim-ramchal":             "asara-prakim-ramchal",
  "kabbala/ramchal/asara-prakim-ilan-hakadosh":       "asara-prakim-ilan-hakadosh",
  "kabbala/ramchal/pirush-vayehi-miketz":             "pirush-vayehi-miketz",
  "kabbala/ramchal/pirush-arimat-yedei":              "pirush-arimat-yedei",
  "kabbala/ramchal/pirush-zohar-mishpatim":           "pirush-zohar-mishpatim",
  "kabbala/ramchal/pirush-mishna-rishona-yetzira":    "pirush-mishna-rishona-yetzira",
  "kabbala/ramchal/klach-pitchei-chochma-ptachim":    "klach-pitchei-chochma-ptachim",
  "kabbala/ramchal/klach-pitchei-chochma":            "klach-pitchei-chochma",
  "kabbala/ramchal/rashei-prakim-divrei-torah":       "rashei-prakim-divrei-torah",
  "kabbala/ramchal/tfilot-pinot-hamerkava":           "tfilot-pinot-hamerkava",

  // ── Ramak ────────────────────────────────────────────────────────────────
  "kabbala/ramak/or-yakar-bereshit":                  "or-yakar-bereshit",
  "kabbala/ramak/or-yakar-nevua":                     "or-yakar-nevua",
  "kabbala/ramak/or-neerav":                          "or-neerav",
  "kabbala/ramak/drishot-malachim":                   "drishot-malachim",
  "kabbala/ramak/sefer-gerushin":                     "sefer-gerushin",
  "kabbala/ramak/pardes-rimonim":                     "pardes-rimonim",
};

// Get English slug for a book path (relative to books/, without .md)
function getSlug(bookPath) {
  const clean = bookPath.replace(/\.md$/, "").replace(/\\/g, "/");
  return SLUG_MAP[clean] || null;
}

module.exports = { SLUG_MAP, getSlug };
